#ifndef PICKOMINO_H
#define PICKOMINO_H

#define NB_JOUEURS_MIN 2
#define NB_JOUEURS_MAX 7

#define NB_DES          8
#define NB_FACE_DES     6
#define FACE_VER        6
#define VALEUR_FACE_VER 5

#define NB_PICKOMINOS        16
#define VALEUR_PICKOMINO_MIN 21
#define VALEUR_PICKOMINO_MAX (NB_PICKOMINOS + VALEUR_PICKOMINO_MIN - 1)
#define PALIER_VER_PICKOMINO 4

#endif